#!/usr/bin/env bash
#
# Start webserver with node's http-server package.
# Node should be installed in a local conda environment and named uac-explorer.
#

source /data/miniconda3/etc/profile.d/conda.sh
conda activate uac-explorer

PORT=${1:-3001}

echo $(which node)

chromium http://127.0.0.1:$PORT &

http-server -c -1 -p $PORT

